import path from "path"
import type { ProjectConfig } from "../config"
import { Filesystem } from "@/util/filesystem"
import { toPascalCase } from "./generate"
import { Process } from "@/util/process"

export interface InitProjectOptions {
  workspace: string
  projectName: string
  config: ProjectConfig
  skipWrapperSetup?: boolean
}

const GRADLE_VERSION = "8.8"
const WRAPPER_TAG = "v8.8.0"
const FORGE_VERSION = "47.4.10"
const MINECRAFT_VERSION = "1.20.1"
const JAVA_VERSION = 17

function buildGradle(config: ProjectConfig) {
  return `plugins {
  id "eclipse"
  id "idea"
  id "maven-publish"
  id "net.minecraftforge.gradle" version "[6.0.24,6.2)"
}

version = "${config.mod.version}"
group = "${config.mod.package}"

base {
  archivesName = "${config.mod.id}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(${JAVA_VERSION})

minecraft {
  mappings channel: "official", version: "${MINECRAFT_VERSION}"
  copyIdeResources = true

  runs {
    configureEach {
      workingDirectory project.file("run")
      mods {
        "${config.mod.id}" {
          source sourceSets.main
        }
      }
    }

    client {
    }
  }
}

repositories {
  mavenCentral()
  maven { url = "https://maven.minecraftforge.net/" }
}

dependencies {
  minecraft "net.minecraftforge:forge:${MINECRAFT_VERSION}-${FORGE_VERSION}"
}

tasks.named("processResources", ProcessResources).configure {
  var replaceProperties = [
    mod_id: "${config.mod.id}",
    mod_name: "${config.mod.name}",
    mod_version: "${config.mod.version}",
    mod_description: "${config.mod.description || "Generated by OpenMods"}",
  ]
  inputs.properties replaceProperties
  filesMatching(["META-INF/mods.toml"]) {
    expand replaceProperties + [project: project]
  }
}
`
}

function gradleWrapperProperties() {
  return `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`
}

function settingsGradle(projectName: string) {
  return `pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url = "https://maven.minecraftforge.net/" }
  }
}

rootProject.name = "${projectName}"
`
}

function forgeMainClass(config: ProjectConfig) {
  const packageName = config.mod.package
  const className = `${toPascalCase(config.mod.id)}Mod`
  return `package ${packageName};

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import ${packageName}.blocks.ModBlocks;
import ${packageName}.items.ModItems;
import ${packageName}.entities.ModEntities;
import ${packageName}.fluids.ModFluids;
import ${packageName}.tileentities.ModBlockEntities;
import ${packageName}.creative_tabs.ModCreativeTabs;
import ${packageName}.enchantments.ModEnchantments;
import ${packageName}.potions.ModEffects;

@Mod("${config.mod.id}")
public class ${className} {
  public ${className}() {
    IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

    ModBlocks.register(modEventBus);
    ModItems.register(modEventBus);
    ModEntities.register(modEventBus);
    ModFluids.register(modEventBus);
    ModBlockEntities.register(modEventBus);
    ModCreativeTabs.register(modEventBus);
    ModEnchantments.register(modEventBus);
    ModEffects.register(modEventBus);

    MinecraftForge.EVENT_BUS.register(this);
  }
}
`
}

function forgeModsToml(config: ProjectConfig) {
  return `modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="${config.mod.id}"
version="${config.mod.version}"
displayName="${config.mod.name}"
description='''${config.mod.description || "Generated by OpenMods"}'''
`
}

async function fetchBytes(url: string) {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`)
  }
  return new Uint8Array(await response.arrayBuffer())
}

async function fetchText(url: string) {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`)
  }
  return await response.text()
}

async function writeGradleWrapperFromGradleRepo(workspace: string) {
  const base = `https://raw.githubusercontent.com/gradle/gradle/${WRAPPER_TAG}`
  const [jar, sh, bat] = await Promise.all([
    fetchBytes(`${base}/gradle/wrapper/gradle-wrapper.jar`),
    fetchText(`${base}/gradlew`),
    fetchText(`${base}/gradlew.bat`),
  ])
  await Filesystem.write(path.join(workspace, "gradle", "wrapper", "gradle-wrapper.jar"), jar)
  await Filesystem.write(path.join(workspace, "gradlew"), sh, 0o755)
  await Filesystem.write(path.join(workspace, "gradlew.bat"), bat)
}

async function writeGradleWrapperWithLocalGradle(workspace: string) {
  const result = await Process.run(["gradle", "wrapper", "--gradle-version", GRADLE_VERSION], {
    cwd: workspace,
    timeout: 120000,
  })
  if (result.code !== 0) {
    throw new Error(result.stderr.toString() || result.stdout.toString() || "gradle wrapper failed")
  }
}

async function ensureGradleWrapper(workspace: string) {
  try {
    await writeGradleWrapperFromGradleRepo(workspace)
    return
  } catch {}
  await writeGradleWrapperWithLocalGradle(workspace)
}

export async function initProject(input: InitProjectOptions) {
  const { workspace, projectName, config, skipWrapperSetup = false } = input
  const packagePath = config.mod.package.replace(/\./g, "/")
  const javaRoot = path.join(workspace, "src", "main", "java", packagePath)
  const resourceRoot = path.join(workspace, "src", "main", "resources")

  await Filesystem.writeJson(path.join(workspace, "openmods.json"), config)
  await Filesystem.write(path.join(workspace, "settings.gradle"), settingsGradle(projectName))
  await Filesystem.write(path.join(workspace, "build.gradle"), buildGradle(config))
  await Filesystem.write(
    path.join(workspace, "gradle", "wrapper", "gradle-wrapper.properties"),
    gradleWrapperProperties(),
  )
  if (skipWrapperSetup) {
    await Filesystem.write(path.join(workspace, "gradlew"), "#!/usr/bin/env sh\nexit 0\n", 0o755)
    await Filesystem.write(path.join(workspace, "gradlew.bat"), "@echo off\r\nexit /b 0\r\n")
  } else {
    await ensureGradleWrapper(workspace)
  }
  await Filesystem.write(path.join(javaRoot, `${toPascalCase(config.mod.id)}Mod.java`), forgeMainClass(config))
  await Filesystem.write(path.join(resourceRoot, "META-INF", "mods.toml"), forgeModsToml(config))
}
