import { z } from "zod"

/**
 * Block Properties Schema
 */
export const BlockPropertiesSchema = z.object({
  hardness: z.number().min(0).default(1.0),
  resistance: z.number().min(0).default(1.0),
  light_level: z.number().int().min(0).max(15).optional(),
  material: z.string().default("STONE"),
  requires_tool: z.boolean().default(true),
  transparent: z.boolean().default(false),
  sound: z.string().default("STONE"),
  harvest_level: z.number().int().min(0).default(0),
  harvest_tool: z.enum(["pickaxe", "axe", "shovel", "hoe", "none"]).default("pickaxe"),
  flammable: z.boolean().default(false),
  friction: z.number().positive().optional(),
  speed_factor: z.number().optional(),
  jump_factor: z.number().optional(),
  has_tile_entity: z.boolean().default(false),
  inventory_size: z.number().int().min(0).optional(),
})

export type BlockProperties = z.infer<typeof BlockPropertiesSchema>

/**
 * Full Block Module Specification
 */
export const BlockSpecSchema = z.object({
  type: z.literal("block"),
  name: z.string().min(1),
  id: z.string().regex(/^[a-z][a-z0-9_]*$/),
  description: z.string().optional(),
  properties: BlockPropertiesSchema.optional(),
})

export type BlockSpec = z.infer<typeof BlockSpecSchema>

/**
 * Material Types
 */
export const MaterialTypes = [
  "AIR",
  "STRUCTURAL_AIR",
  "PLANT",
  "REPLACEABLE_PLANT",
  "REPLACEABLE_FIREPROOF_PLANT",
  "REPLACEABLE_WATER_PLANT",
  "WATER",
  "BUBBLE_COLUMN",
  "LAVA",
  "TOP_SNOW",
  "FIRE",
  "DEBRIS",
  "ICE",
  "PACKED_ICE",
  "SNOW",
  "STONE",
  "METAL",
  "HEAVY_METAL",
  "BARRIER",
  "WOOL",
  "BUILDING_GLASS",
  "GRASS",
  "DIRT",
  "SAND",
  "SPONGE",
  "SHULKER_SHELL",
  "WOOD",
  "NETHER_WOOD",
  "BAMBOO_SAPLING",
  "BAMBOO",
  "BAMBOO_STALK",
  "CLAY",
  "VEGETABLE",
  "CAKE",
  "AMETHYST",
  "POWDER_SNOW",
  "SCULK",
  "EGG",
  "FROGSPAWN",
  "FROG_LIGHT",
] as const

export type MaterialType = typeof MaterialTypes[number]

/**
 * Sound Types
 */
export const SoundTypes = [
  "AMETHYST_BLOCK",
  "AMETHYST_CLUSTER",
  "ANCIENT_DEBRIS",
  "ANVIL",
  "AZALEA",
  "AZALEA_LEAVES",
  "BAMBOO",
  "BAMBOO_SAPLING",
  "BASALT",
  "BEACON",
  "BED",
  "BEEHIVE",
  "BELL",
  "BIG_DRIPLEAF",
  "BONE_BLOCK",
  "CALCITE",
  "CANDLE",
  "CAVE_VINES",
  "CHAIN",
  "CHERRY_LEAVES",
  "CHERRY_SAPLING",
  "CHERRY_WOOD_HANGING_SIGN",
  "CHERRY_WOOD",
  "CHISELED_BOOKSHELF",
  "CLOTH",
  "COARSE_DIRT",
  "COPPER",
  "CORAL_BLOCK",
  "CROP",
  "DECORATED_POT",
  "DEEPSLATE",
  "DEEPSLATE_BRICKS",
  "DRIPSTONE_BLOCK",
  "ENCHANTMENT_TABLE",
  "END_PORTAL_FRAME",
  "ENDER_CHEST",
  "FENCE_GATE",
  "FIRE",
  "FLOWERING_AZALEA",
  "FUNGI",
  "FUNGUS",
  "GILDED_BLACKSTONE",
  "GLASS",
  "GLOW_LICHEN",
  "GLOWSTONE",
  "GRASS",
  "GRAVEL",
  "GRINDSTONE",
  "HANGING_ROOTS",
  "HANGING_SIGN",
  "HARD_CROP",
  "HEAVY_CORE",
  "HONEY_BLOCK",
  "HONEYCOMB",
  "INK_SAC",
  "IRON",
  "LADDER",
  "LANTERN",
  "LARGE_AMETHYST_BUD",
  "LAVA",
  "LEAVES",
  "LEVER",
  "LIGHT",
  "LIGHTNING_ROD",
  "LILY_PAD",
  "LODESTONE",
  "MANGROVE_ROOTS",
  "MEDIUM_AMETHYST_BUD",
  "METAL",
  "MOSS",
  "MOSS_CARPET",
  "MUD",
  "MUD_BRICKS",
  "MUDDY_MANGROVE_ROOTS",
  "NETHER_BRICKS",
  "NETHER_GOLD_ORE",
  "NETHER_ORE",
  "NETHER_SPROUTS",
  "NETHER_WART",
  "NETHERITE_BLOCK",
  "NETHERRACK",
  "NETHER_WOOD_HANGING_SIGN",
  "NETHER_WOOD",
  "NOTE_BLOCK",
  "NYLIUM",
  "PACKED_MUD",
  "POLISHED_DEEPSLATE",
  "PORTAL",
  "POTATOES",
  "POWDER_SNOW",
  "PUMPKIN",
  "ROOTS",
  "ROOTED_DIRT",
  "SAND",
  "SCAFFOLDING",
  "SCULK",
  "SCULK_CATALYST",
  "SCULK_SENSOR",
  "SCULK_SHRIEKER",
  "SCULK_VEIN",
  "SHROOMLIGHT",
  "SHULKER_BOX",
  "SLIME_BLOCK",
  "SMALL_AMETHYST_BUD",
  "SMALL_DRIPLEAF",
  "SMITHING_TABLE",
  "SNOW",
  "SOUL_SAND",
  "SOUL_SOIL",
  "SPORE_BLOSSOM",
  "STEM",
  "STONE",
  "SWEET_BERRY_BUSH",
  "SUSPICIOUS_GRAVEL",
  "SUSPICIOUS_SAND",
  "SWAMP_CROP",
  "TARGET",
  "TUFF",
  "TWISTING_VINES",
  "VINE",
  "WART_BLOCK",
  "WEEPING_VINES",
  "WET_GRASS",
  "WET_SPONGE",
  "WOOD",
  "WOOL",
] as const

export type SoundType = typeof SoundTypes[number]